
            
---
- name: Gather OS details and installed packages
  hosts: all
  become: yes
  tasks:
    - name: Show OS details
      ansible.builtin.command:
        cmd: uname -a
      register: os_details

    - name: Print OS details
      ansible.builtin.debug:
        msg: "OS Details: {{ os_details.stdout }}"

    - name: Get Red Hat OS version
      ansible.builtin.command:
        cmd: cat /etc/redhat-release
      register: os_version

    - name: Print Red Hat version
      ansible.builtin.debug:
        msg: "OS Version: {{ os_version.stdout }}"

    - name: List installed packages
      ansible.builtin.yum:
        list: installed
      register: installed_packages

    - name: Print installed packages
      ansible.builtin.debug:
        msg: "Installed Packages: {{ installed_packages.results | map(attribute='name') | join(', ') }}"
