---
- name: Configure Web Server
  hosts: webservers
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: "{{ service_name }}"
        state: present

    - name: Create Document Root
      ansible.builtin.file:
        path: "{{ document_root }}"
        state: directory

    - name: Create Admin User
      ansible.builtin.user:
        name: "{{ admin_user }}"
        state: present
